setTimeout(()=>{
    document.getElementById("counts").innerHTML="10";
    setTimeout(()=>{
        document.getElementById("counts").innerHTML="9"
        setTimeout(()=>{
            document.getElementById("counts").innerHTML="8";
            setTimeout(()=>{
                document.getElementById("counts").innerHTML="7";
                setTimeout(()=>{
                    document.getElementById("counts").innerHTML="6";
                    setTimeout(()=>{
                        document.getElementById("counts").innerHTML="5";
                        setTimeout(()=>{
                            document.getElementById("counts").innerHTML="4";
                            setTimeout(()=>{
                                document.getElementById("counts").innerHTML="3";
                                setTimeout(()=>{
                                    document.getElementById("counts").innerHTML="10";
                                    setTimeout(()=>{
                                        document.getElementById("counts").innerHTML="10";
                                        setTimeout(()=>{
                                            document.getElementById("counts").innerHTML="Happy Independence Day";
                                        },1000)
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
},0)